
-- Habilita RLS (Row Level Security) para segurança
-- ALTER TABLE sales_history ENABLE ROW LEVEL SECURITY; -- Comentado para evitar erros se já executado

-- Cria a tabela de histórico de vendas se ela não existir
CREATE TABLE IF NOT EXISTS public.sales_history (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    external_id TEXT UNIQUE, -- ID único do sistema externo (Olist/Bling)
    order_number TEXT,
    sale_date TIMESTAMPTZ,
    expected_date TIMESTAMPTZ,
    status TEXT,
    notes TEXT,
    contact_id TEXT,
    contact_name TEXT,
    person_type TEXT,
    cpf_cnpj TEXT,
    rg_ie TEXT,
    email TEXT,
    phone TEXT,
    mobile TEXT,
    zip_code TEXT,
    address TEXT,
    address_number TEXT,
    complement TEXT,
    neighborhood TEXT,
    city TEXT,
    state TEXT,
    product_id_external TEXT,
    sku TEXT,
    description TEXT,
    quantity NUMERIC,
    unit_price NUMERIC,
    item_discount NUMERIC,
    order_discount NUMERIC,
    order_freight NUMERIC,
    order_expenses NUMERIC,
    prorated_discount NUMERIC,
    prorated_freight NUMERIC,
    prorated_expenses NUMERIC,
    tracking_code TEXT,
    sales_rep TEXT,
    purchase_order_number TEXT,
    recipient_name TEXT,
    recipient_cpf_cnpj TEXT,
    recipient_zip_code TEXT,
    recipient_address TEXT,
    recipient_address_number TEXT,
    recipient_complement TEXT,
    recipient_neighborhood TEXT,
    recipient_city TEXT,
    recipient_state TEXT,
    recipient_phone TEXT,
    imported_at TIMESTAMPTZ DEFAULT NOW(),
    total_amount NUMERIC,
    total_freight NUMERIC
);
